exports.invoices = [
  {
    id: 1,
    sender_name: 'Jonny',
    to_email: 'test@test.com',
    project_name: 'Flex Ride',
    invoice_type: 'one-time',
    description: 'Flex Ride Flex Ride Flex Ride',
    total_cost: 100,
    status: 'paid',
  },
  {
    id: 2,
    sender_name: 'Jonny',
    to_email: 'test@test.com',
    project_name: 'Flex Ride',
    invoice_type: 'one-time',
    description: 'Flex Ride Flex Ride Flex Ride',
    total_cost: 100,
    status: 'unpaid',
  },
  {
    id: 3,
    sender_name: 'Jonny',
    to_email: 'test@test.com',
    project_name: 'Flex Ride',
    invoice_type: 'one-time',
    description: 'Flex Ride Flex Ride Flex Ride',
    total_cost: 100,
    status: 'paid',
  },
];
