export const CHANGE_NAME = 'CHANGE_NAME';
export const SET_INVOICES = 'SET_INVOICES';
export const CHANGE_TAB = 'CHANGE_TAB';
export const INVOICE_UPDATE = 'INVOICE_UPDATE';
export const START_REQUEST = 'START_REQUEST';
export const REQUEST_SUCCESS = 'REQUEST_SUCCESS';
export const REQUEST_ERROR = 'REQUEST_ERROR';
export const LOAD_CLIENTS = 'LOAD_CLIENTS';
