export const CHANGE_NAME = 'CHANGE_NAME';
export const CHANGE_TAB = 'CHANGE_TAB';
export const INVOICE_UPDATE = 'INVOICE_UPDATE';
export const START_SUBMISSION = 'START_SUBMISSION';
export const SUBMISSION_SUCCESS = 'SUBMISSION_SUCCESS';
export const SUBMISSION_ERROR = 'SUBMISSION_ERROR';
